[package]
name = "codec-rust"
version = "0.1.0"
authors = ["alesiong <ypf7.10@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# clap = { version = "2.33", features = [], default-features = false }
bytebuffer = "0.2.1"
pipe = "0.3.0"