name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Build Release
      run: cargo build --release --verbose
    # - name: Run tests
    #   run: cargo test --verbose

    - name: Upload Build
      uses: actions/upload-artifact@master
      with:
        name: codec-rust-${{matrix.os}}
        path: target/release/codec-rust